### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by sirkitree** [Lullabot/lullabot-slackbot#19]
It would be great to have some documentation (readme or wiki) on how and where this is deployed currently and how one might test this - like should I create a new bot/slack key for testing changes before incorporating them into the main Lullabot?
```[tasklist]
### Tasks
- [ ] How to contribute
- [ ] How to deploy
- [ ] Where Lullabot is deployed
- [ ] How to test proposed changes
```
